apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
spec:
  instances: 1

  storage:
    size: 1Gi

  imageName: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

    # This extension is loaded via the Database CRD at cloudnative-pg-database.yaml
    extensions:
      - name: vchord
        image:
          reference: ghcr.io/tensorchord/vchord-scratch:pg18-v1.1.1
        dynamic_library_path:
          - /usr/lib/postgresql/18/lib
        extension_control_path:
          - /usr/share/postgresql/18/

