apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
spec:
  instances: 1

  storage:
    size: 1Gi

  imageName: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie

  # IMPORTANT: Mount the extension (spec.postgresl.extensions) and apply BEFORE configuring shared_preload_libraries here
  # ref: https://cloudnative-pg.io/documentation/current/imagevolume_extensions/#how-to-add-a-new-extension
  postgresql:
    shared_preload_libraries:
      - "vchord.so"

    extensions:
      - name: vchord
        image:
          reference: ghcr.io/tensorchord/vchord-scratch:pg18-v0.5.3
        dynamic_library_path:
          - /usr/lib/postgresql/18/lib
        extension_control_path:
          - /usr/share/postgresql/18/

