## This chart relies on the common library chart from bjw-s
## You can find it at https://github.com/bjw-s-labs/helm-charts/tree/common-5.0.1/charts/library/common
## Refer there for more detail about the supported values

# These entries are shared between all the Immich components

controllers:
  main:
    containers:
      main:
        image:
          tag: v3.0.0
        env:
          REDIS_HOSTNAME: '{{ printf "%s-valkey" .Release.Name }}'
          IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'
          # Add the env vars to connect to your database here. see the example below
          #
          # DB_HOSTNAME: immich-postgresql-rw
          # DB_USERNAME: immich
          # DB_DATABASE_NAME: immich
          # DB_PASSWORD:
          #   valueFrom:
          #     secretKeyRef:
          #       name: immich-postgres-user
          #       key: password

immich:
  metrics:
    # Enabling this will create the service monitors needed to monitor immich with the prometheus operator
    enabled: false
  persistence:
    # Main data store for all photos shared between different components.
    library:
      # Automatically creating the library volume is not supported by this chart
      # You have to specify an existing PVC to use
      existingClaim:
  # configuration is immich-config.json converted to yaml. Ignored if existingConfiguration is set.
  # ref: https://immich.app/docs/install/config-file/
  #
  configuration: {}
    # trash:
    #   enabled: false
    #   days: 30
    # storageTemplate:
    #   enabled: true
    #   template: "{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}"
  # Sets the resource Kind to store configuration in. Must be either ConfigMap or Secret.
  configurationKind: ConfigMap

  # Specify existing configuration resource name here to skip creation of a new one
  # existingConfiguration:

# Dependencies

valkey:
  enabled: false
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/valkey/valkey
            tag: 9.1-alpine@sha256:a35428eba9043cc0b79dbe54100f0c92784f2de00ad09b01182bfb1c5c83d1bd
            pullPolicy: IfNotPresent
  persistence:
    data:
      enabled: true
      type: emptyDir
      # Optional: to keep job queues persistent, replace `type: emptyDir` above with:
      #   type: persistentVolumeClaim
      #   size: 1Gi
      #   accessMode: ReadWriteOnce
      #   # storageClass: your-class

# Immich components

server:
  enabled: true
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/immich-app/immich-server
            pullPolicy: IfNotPresent
  ingress:
    main:
      enabled: false
      annotations:
        # proxy-body-size is set to 0 to remove the body limit on file uploads
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - host: immich.local
          paths:
            - path: "/"
              service:
                identifier: main
      tls: []

machine-learning:
  enabled: true
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/immich-app/immich-machine-learning
            pullPolicy: IfNotPresent
          env:
            TRANSFORMERS_CACHE: /cache
            HF_XET_CACHE: /cache/huggingface-xet
            MPLCONFIGDIR: /cache/matplotlib-config
  persistence:
    cache:
      enabled: true
      type: emptyDir
      # Optional: to avoid downloading the ML models on every start, replace `type: emptyDir` above with:
      #   type: persistentVolumeClaim
      #   size: 10Gi
      #   accessMode: ReadWriteMany
      #   # storageClass: your-class
