name: Zizmor

on:
  pull_request:
  push:
    branches: [main]

jobs:
  zizmor:
    name: Zizmor
    uses: immich-app/devtools/.github/workflows/shared-zizmor.yml@f88698ef64e40a764b4b7a81eae5f76634f53a6c # main
    permissions:
      actions: read
      contents: read
      security-events: write
