name: Zizmor

on:
  pull_request:
  push:
    branches: [main]

jobs:
  zizmor:
    name: Zizmor
    uses: immich-app/devtools/.github/workflows/shared-zizmor.yml@7225d10fecbb4a77b74266f7be12725449885a1e # main
    permissions:
      actions: read
      contents: read
      security-events: write
